* Basic German

** Unit 3

- Du atmest sehr heftig.

- Herr Maier arbeitet bei Siemens

- Es regnet schon wieder

- Ihr redet zu viel.

- Du fährt morgen nach Hause.

- Gleich fällt es runter.

*** Ablaut

- a -> ä

- e -> i

- e -> ie

halten - hältst, hält

** Unit 5

- Das Meeting findet am Montag statt.

** Unit 6

imperative: seien, warte, atme, sprich, lies, fahr, trag

Mein Geburtstag ist am vierten sechsten/Juni.

** Unit 7

"wie" is also used when asking for a name or address/nationality, where using "was" is incorrect.

- Wie ist dein Name?

- Wie ist Ihre Telefonnummer/Adresse?

** Unit 8

Alcoholic drinks, makes of cars tend to be masculine. 

Names of trees and flowers tend to be feminine, and so are names of names of motorbikes and ships.

Names of most metals tend to be neuter.

** Unit 9

The great majority of masculine nouns form their plural by adding -e, sometimes with an umlaut. Nouns ending in -er, -el or -en have nochange or sometimes with an umlaut.

The huge majority (90%) of feminine nouns add -n or -en. A number of commonly used feminine nouns add umlaut + -e.

Most neuter nouns add -e but no umlaut. Another common ending is -er with an umlaut.

** Unit 13

helfen, danken, gehören, folgen

For dative case, plural endings are -en added to the modifier and -en or -n added to the noun.

** Unit 14

For genetive, masculine and neuter nouns add -es to most short nouns, and usually -s to nouns with two or more syllables.

trotz, während, wegen, (an)statt

** Unit 15

er - ihn - ihm
sie - sie - ihr
es - es - ihm
sie/Sie - sie/Sie - ihnen
ihr - euch - euch
