# Turn off default internal styles
#+OPTIONS: html-style:nil html5-fancy:t

# Exporting to HTML5
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <meta http-equiv="X-UA-Compatible" content="IE=edge">
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1">

# Add notes.css here
#+HTML_HEAD: <link href="http://taopeng.me/org-notes-style/css/notes.css" rel="stylesheet" type="text/css" />


* Basic German

** Unit 3

- Du atmest sehr heftig.

- Herr Maier arbeitet bei Siemens

- Es regnet schon wieder

- Ihr redet zu viel.

- Du fährt morgen nach Hause.

- Gleich fällt es runter.

*** Ablaut

- a -> ä

- e -> i

- e -> ie

halten - hältst, hält

** Unit 5

- Das Meeting findet am Montag statt.

** Unit 6

imperative: seien, warte, atme, sprich, lies, fahr, trag

Mein Geburtstag ist am vierten sechsten/Juni.

** Unit 7

"wie" is also used when asking for a name or address/nationality, where using "was" is incorrect.

- Wie ist dein Name?

- Wie ist Ihre Telefonnummer/Adresse?

** Unit 8

Alcoholic drinks, makes of cars tend to be masculine. 

Names of trees and flowers tend to be feminine, and so are names of names of motorbikes and ships.

Names of most metals tend to be neuter.

** Unit 9

The great majority of masculine nouns form their plural by adding -e,
 sometimes with an umlaut. Nouns ending in -er, -el or -en have no change or sometimes with an umlaut.

The huge majority (90%) of feminine nouns add -n or -en. 
A number of commonly used feminine nouns add umlaut + -e.

Most neuter nouns add -e but no umlaut. Another common ending is -er with an umlaut.

** Unit 13

helfen, danken, gehören, folgen

For dative case, plural endings are -en added to the modifier and -en or -n added to the noun.

** Unit 14

For genitive, masculine and neuter nouns add -es to most short nouns, and usually -s to nouns with two or more syllables.

trotz, während, wegen, (an)statt

** Unit 15

- er - ihn - ihm

- sie - sie - ihr

- es - es - ihm

- sie/Sie - sie/Sie - ihnen

- ihr - euch - euch

** Unit 17

amüsieren, anziehen, ausziehen, beeilen, duschen, entscheiden, entschuldigen, kämmen, rasieren, schminken, treffen, umziehen, waschen

- Ich ziehe mich an; Ich ziehe mir eine Jacke an.

** Unit 18

nicht: in the present tense usually follows the finite verb. It may be preceded by an expression of time. 

** Unit 19

+ alt - älter

+ arm - ärmer

+ jung - jünger

+ groß - größer

+ kalt - kälter - kältest

+ kurz - kürzer - kürzest

+ lang - länger

+ stark - stärker

+ warm - wärmer

+ hoch - höher - höchsten

+ gern - lieber - am liebsten

am + superlative is used as the adverb form of the corresponding superlative adjective

** Unit 20

- dürfen: expresses permission; ich darf, du darfst, ihr dürft, er/sie/es darf, etc. dürfen

Sie dürfen hier rauchen.

Darf ich Ihnen helfen.

To say "you must not", use dürfen + nicht:

Du darfst nicht rauchen.

- wollen: ich/es/sie/es will, du willst, ihr wollt, wollen for the others

- mögen/möchten: to like/would like; ich/es/sie/es mag, du magst  

** Unit 21

Strong verbs form their past participle in most cases by adding ge- to the stem and -en at the end. The majority also have a stem vowel change.

- finden -> gefunden

- helfen -> geholfen

- schreiben -> geschrieben

- trinken - getrunken

Mixed verbs have a stem change but add -t instead of -en.

- bringen -> gebracht

- denken -> gedacht

- wissen -> gewusst

with sein:

- fahren, fliegen (geflogen), gehen, kommen, laufen (gelaufen), schwimmen (geschommen), reisen, bleiben (geblieben), sterben (gestorben), werden (geworden) 
