* Intro

旁白：  幻想乡，结界所隔开的、存在于现代背后的另一个世界，是人类、妖精、妖怪、神都可以和睦相处的世外桃源。
每年热天来了，守结界的巫女博丽灵梦的神社博丽神社就要举办一场大宴会。神社头尽是幻想乡的居民。今年子，
幻想乡的热天又来了。

* OP


* 博丽神社仓库

萃香： 喂，灵梦，风铃！找到风铃了。灵梦？

灵梦： 萃香，那面架架高底的盆盆儿你帮我lao3下嘛。

萃香: 哦，在哪儿？

萃香：（找到盆盆儿）这儿嗦。

灵梦： 说是说要早点起来准备宴会，但是就寡是萃香一个来帮忙了。萃香！（萃香栽下来）看就晓得要成啥子样儿。

灵梦： 搞快！要走了。（萃香撞门）哎……。

灵梦： 好生拿倒！

萃香： 欸！

萃香： 灵梦！这里头没得酒欸！

灵梦： 啊？

萃香： 我要酒，要酒，要酒！

灵梦： 你硬是……等今晚些吃饭你想喝好多喝好多，等下儿就去买嘛。

萃香： m1mn2

灵梦： 哎3……硬是不好打整。等下儿的活路我一个人干，你就跟我跑个路买下东西，跑个路。

萃香： ___

灵梦： 找的零钱要给我哈！

萃香： 我晓得了！

* 神社前

灵梦： 这下儿就先这些嘛。还有吗就是……是……啊(an1）？！啷子？！我的钱箱箱儿ae1？

* 鸟居底下

灵梦： 没得……没得……没得……都找交了还是没得。得不得是着……

文： 着哪个偷起去了。

灵梦： 对啊，就是，着偷起去了。

文： ___

灵梦： ___！是文嗦。

文： （笑）早晨好！

灵梦： 你在这儿干啥子？

文： 喂灵梦，你好生想下嘛，你当真觉得，幻想乡有哪个其他不偷硬要你这个钱箱箱儿的？

灵梦： 欸……你莫要说了。你莫要(mao4)管里头有啥子，反正就是没得了。

文： 是感觉不当啷子可能，但是硬就是恁子欸。但是你也莫要慌，我也帮你找下哪个干的嘛。

灵梦： 不消你！我一个人照样找得到。反正你还不是半边照几张照片。

文： 喂！我啷子吗也是个正儿八经的记者。论收集情报的水平吗我是幻想乡第一得嘛。是嘛！好，现在最新的消息是这个……

灵梦： 欸……这下儿我从哪儿开始找ae1？

文： 欸……我一个人你觉得不够啊？

灵梦： 听不倒，听不倒。

文： 好嘛懂哇，我再找帮手的来嘛。

灵梦： 啊an1？

文： 灵梦你在这儿等下哈！

灵梦： 等下，文！喂……

文： 冇来头，你等我五秒我就转来。

灵梦： 你究竟啷子搞？

文： 风神少女！

灵梦：e2... 等下……

文： 报告我回来了！

灵梦： 是快哈3。魔理沙？没得事嘛？

魔理沙： 差点就着你整倒了住。

文： 哦，那个…… 就是那个着搞落哇的钱箱箱儿，我不敢肯定，但是偷箱箱儿的人说不定就是我们身面前哪个。

魔理沙： _， 我讲清楚哈不是得我偷的哈。

文： 我从头到尾就没有怀疑你魔理沙。因为你昨天一直都跟我一起得嘛。

魔理沙： 那个……还不是你一直喊倒我跟你做报纸。

灵梦： 你们两个。尽倒在这儿扯这些，先把东西找倒do1。搞快点。

文： 

魔理沙： 等下do1，我几时成了给你们找钱箱箱儿打下手的了？我反反复复讲了好几遍不去的。

文： 你当真觉得这种话你讲得啊？你魔理沙那些见不得人的照片就要公之于众了。灵梦看倒了要想些啥子我不晓得哦。

魔理沙： 

文： 哪儿没对啊？

魔理沙： 我感觉刚才有人din2倒我们。

文： 我啷子没感觉倒.

魔理沙： 我还是觉得莫要管这个事情好些，感觉事情没得好对头。

文： 你心理作用了。你是想到啥子了啊？

灵梦：你两个，快点过来。

魔理沙：不是得想到啥子……

文： 要得！马上来！

* 神社前

萃香： 喂灵梦，我回来了，东西买倒了，耶？灵梦ae1？

* 红魔馆门口

魔理沙： 灵梦，我问你ae3。

灵梦： 问啥子嘛？

魔理沙： 你找个钱箱箱儿啷子要跑倒红魔馆来？

灵梦： 文跟我讲帕秋莉行为可疑。

魔理沙： 帕秋莉？是那个帕秋莉啊？

灵梦： 啊（a2）。她敢lao3倒当书架的话你看我啷子收拾她。她硬是……

魔理沙： 不晓得哪个才可能把箱箱儿当书架用。惹fan2了我是不管的哈。文，你又在干啥子哦？

文： 拍照片唦！

魔理沙： 这个我还是看得出来……莫要拍了，过来了！

* 阳台

蕾米莉亚： 今早晨那个，不晓得究竟是啷子了。



咲夜： 红茶啊？不好意思，茶叶……

蕾米莉亚： 茶叶没在了？

咲夜： 欸(e2), 葡萄酒跟其他____昨晚些一下也没在了。

蕾米莉亚： 未必是哪个进来偷起去了啊？

咲夜： 我先前也是恁子想的。但是点声音都没得，而且一晚上那么(lam1）多。

蕾米莉亚： ____



魔理沙： 那个钱箱箱儿有那么重要啊？

灵梦： 魔理沙，你不晓得！

魔理沙： 但是里头基本没得钱得嘛。

灵梦： 有没得不是得重点。重点是那个箱箱儿。

蕾米莉亚： 灵梦跟魔理沙？她们来干啥子？

文： 就是来办点小事情。__，这个，_____________

魔理沙： 喂，文！你在哪儿？

文： 读煞角了等下儿要跟我讲下感想哈。__

蕾米莉亚： 感想啊……博丽神社，宴会中止

* 图书馆里头

帕秋莉： 没对啊，是该在这儿的。不是得这个。____

灵梦： 帕秋莉！进来了哈！

魔理沙： 进都进来了。

文： 这儿稀奇的书好多哦！我这下儿晓得魔理沙为啥子借了书不还了。

魔理沙： 你讲话跟人留点面子嘛。

灵梦： 喂帕秋莉，你在唦？在哪儿？哦，这儿啊。其实我是有点事情要问你。

帕秋莉： 哦，不好意思，我这下儿_______。你要找人伙倒耍去找Flan。

灵梦： 好嘛，你老实交代吗我可以考虑下。

帕秋莉：啊？

灵梦： ___,_!

帕秋莉：手伸起干啥子？

灵梦：把我钱箱箱儿还给我。

帕秋莉： 啊？你讲啥……讲些啥……啥子哟？_______

灵梦： 喂帕秋莉！我话没讲煞角，你_____。帕秋莉？

帕秋莉： 你……你些_____

* 阳台

蕾米莉亚： __________，博丽灵梦，由于其神社的赛钱箱被盗而展开调查，并决定取消今晚的宴会。未必是？

咲夜： 蕾米莉亚小姐，下午茶好了。

蕾米莉亚： 哦，咲夜，红茶啊，你找到了啊？

咲夜： 不好意思，换了冰可可。

蕾米莉亚： 哦……尽快找得到最好。

咲夜： 是，我也想。

蕾米莉亚： 还有就是，Patchy也讲她有些书没在了。咲夜？咲夜！

咲夜： 不好意思，我刚刚听到底下的声音感觉有点不对头。

蕾米莉亚： 哦，灵梦她们来了，肯定是她们。

咲夜： 中国，不，美玲的话，她又______，我还是去看下。

蕾米莉亚： 咲夜你莫要慌。______?

* 图书馆里头

帕秋莉： ________，spell card！ ______， Royal Flare!

灵梦： 嘿，得行嘛。

帕秋莉： 啷子？！我的魔法墙！

灵梦：____________！Spell card！灵符“梦想封印”！跑脱了嗦。

帕秋莉： 到底搞些啥子嘛，把我的图书馆弄得乱七八糟。

咲夜： 帕秋莉小姐，我是咲夜，






